# Generated by Django 4.0.4 on 2022-04-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='expiration_time',
            new_name='end_time',
        ),
    ]
